openapi: 3.2.0
info:
  title: Confluent Kafka REST Proxy Broker API
  description: The Kafka REST Proxy provides a RESTful interface to an Apache Kafka cluster, making it easy to produce and consume messages, view the state of the cluster, and perform administrative actions without using the native Kafka protocol or clients.
  version: 3.0.0
  contact:
    name: Apache Kafka
    url: https://kafka.apache.org/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
- url: http://localhost:8082
  description: Default Kafka REST Proxy
tags:
- name: Broker
paths:
  /clusters/{cluster_id}/brokers:
    get:
      summary: Apache kafka List Brokers
      operationId: listBrokers
      tags:
      - Broker
      parameters:
      - name: cluster_id
        in: path
        required: true
        schema:
          type: string
        example: item-2365
      responses:
        '200':
          description: List of brokers
          content:
            application/json:
              schema:
                type: object
                properties:
                  kind:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Broker'
              examples:
                listBrokers200Example:
                  summary: Default listBrokers 200 response
                  x-microcks-default: true
                  value:
                    kind: example-value
                    data: []
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    Broker:
      type: object
      properties:
        kind:
          type: string
        metadata:
          type: object
        cluster_id:
          type: string
        broker_id:
          type: integer
        host:
          type: string
        port:
          type: integer
