openapi: 3.2.0
info:
  title: Confluent Kafka REST Proxy Records API
  description: The Kafka REST Proxy provides a RESTful interface to an Apache Kafka cluster, making it easy to produce and consume messages, view the state of the cluster, and perform administrative actions without using the native Kafka protocol or clients.
  version: 3.0.0
  contact:
    name: Apache Kafka
    url: https://kafka.apache.org/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
- url: http://localhost:8082
  description: Default Kafka REST Proxy
tags:
- name: Records
paths:
  /topics/{topic_name}/records:
    post:
      summary: Apache kafka Produce Records to a Topic
      operationId: produceRecords
      tags:
      - Records
      parameters:
      - name: topic_name
        in: path
        required: true
        schema:
          type: string
        example: example-name
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProduceRequest'
            examples:
              produceRecordsRequestExample:
                summary: Default produceRecords request
                x-microcks-default: true
                value:
                  partition_id: 46
                  headers: []
                  key: {}
                  value: {}
      responses:
        '200':
          description: Records produced
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProduceResponse'
              examples:
                produceRecords200Example:
                  summary: Default produceRecords 200 response
                  x-microcks-default: true
                  value:
                    error_code: 17
                    cluster_id: item-5744
                    topic_name: example-name
                    partition_id: 25
                    offset: 62
                    timestamp: '2025-03-15T14:30:00Z'
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
components:
  schemas:
    ProduceResponse:
      type: object
      properties:
        error_code:
          type: integer
        cluster_id:
          type: string
        topic_name:
          type: string
        partition_id:
          type: integer
        offset:
          type: integer
        timestamp:
          type: string
          format: date-time
    ProduceRequest:
      type: object
      properties:
        partition_id:
          type: integer
        headers:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              value:
                type: string
        key:
          type: object
          properties:
            type:
              type: string
              enum:
              - BINARY
              - JSON
              - AVRO
              - PROTOBUF
              - JSONSCHEMA
            data: {}
        value:
          type: object
          properties:
            type:
              type: string
              enum:
              - BINARY
              - JSON
              - AVRO
              - PROTOBUF
              - JSONSCHEMA
            data: {}
